-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.searchcontents(search text)
--  RETURNS SETOF content
--  LANGUAGE sql
--  STABLE
-- AS $function$
--     SELECT *
--     FROM content
--     WHERE
--       search <% (title || ' ' || body)
--     ORDER BY
--       similarity(search, (title || ' ' || body)) DESC
--     LIMIT 5;
-- $function$;
